language: ruby

jobs:
  include:
    - stage: "Run tests"
      name: "Run tests - unit"
      script: bundle exec rspec ./spec/unit
    - script: bundle exec rspec ./spec/acceptance
      name: "Run tests - acceptance"
